<%@ Page Title="" Language="C#" MasterPageFile="~/Master/AdminMaster.master" AutoEventWireup="true" CodeFile="AsignRole.aspx.cs" Inherits="PageAdmin_AsignRole" %>

<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="asp" %>

<asp:Content ID="Content1" ContentPlaceHolderID="contentuser" runat="Server">
    <style type="text/css">
        .fancy-green .ajax__tab_header {
            background: url('../Images/green_bg_Tab.gif') repeat-x;
            cursor: pointer;
        }

        .fancy-green .ajax__tab_hover .ajax__tab_outer, .fancy-green .ajax__tab_active .ajax__tab_outer {
            background: url('../Images/green_left_Tab.gif') no-repeat left top;
        }

        .fancy-green .ajax__tab_hover .ajax__tab_inner, .fancy-green .ajax__tab_active .ajax__tab_inner {
            background: url('../Images/green_right_Tab.gif') no-repeat right top;
        }

        .fancy .ajax__tab_header {
            font-size: 13px;
            font-weight: bold;
            color: #000;
            font-family: sans-serif;
        }

            .fancy .ajax__tab_active .ajax__tab_outer, .fancy .ajax__tab_header .ajax__tab_outer, .fancy .ajax__tab_hover .ajax__tab_outer {
                height: 46px;
            }

            .fancy .ajax__tab_active .ajax__tab_inner, .fancy .ajax__tab_header .ajax__tab_inner, .fancy .ajax__tab_hover .ajax__tab_inner {
                height: 46px;
                margin-left: 16px; /* offset the width of the left image */
            }

            .fancy .ajax__tab_active .ajax__tab_tab, .fancy .ajax__tab_hover .ajax__tab_tab, .fancy .ajax__tab_header .ajax__tab_tab {
                margin: 16px 16px 0px 0px;
            }

        .fancy .ajax__tab_hover .ajax__tab_tab, .fancy .ajax__tab_active .ajax__tab_tab {
            color: #fff;
        }

        .fancy .ajax__tab_body {
            font-family: Arial;
            font-size: 10pt;
            border-top: 0;
            border: 1px solid #999999;
            padding: 8px;
            background-color: #ffffff;
        }

        .but {
            border-radius: 8px;
            border-style: groove;
            height: 38px;
            width: 120px;
            background-color: #2762f7;
            color: whitesmoke;
            font-size: medium;
            margin-top: 15px;
            vertical-align: central;
            text-align: center;
        }
    </style>
    <asp:ToolkitScriptManager ID="ToolkitScriptManager1" runat="server"></asp:ToolkitScriptManager>
    <div id="content">
        <div style="width: 70%">
            <asp:TabContainer ID="TabContainer1" runat="server" ActiveTabIndex="0" CssClass="fancy fancy-green" TabStripPlacement="Top">
                <asp:TabPanel ID="TabPanel1" runat="server">
                    <HeaderTemplate>Create Role</HeaderTemplate>
                    <ContentTemplate>
                        <table align="center">
                            <tr>
                                <td><b>Enter RoleName:</b> </td>
                                <td>
                                    <asp:TextBox ID="txtRole" runat="server" />
                                    <asp:RequiredFieldValidator ControlToValidate="txtRole" ForeColor="Red" ID="req" runat="server" ErrorMessage="*" ValidationGroup="myg"></asp:RequiredFieldValidator>
                                </td>
                            </tr>
                            <tr>
                                <td></td>
                                <td>
                                    <asp:Button ID="btnCreate" runat="server" Text="Create Role" OnClick="btnCreate_Click" ValidationGroup="myg" /></td>
                            </tr>
                            <tr>
                                <td colspan="2">
                                    <asp:Label ID="lblResult" runat="server" Font-Bold="true" /></td>
                            </tr>
                            <tr>
                                <td colspan="2">
                                    <asp:GridView ID="gvRoles" runat="server" CssClass="Gridview" Width="200" AutoGenerateColumns="false" AutoGenerateDeleteButton="true" OnRowDeleting="gvRoles_RowDeleting">
                                        <HeaderStyle BackColor="#df5015" />
                                        <Columns>
                                            <asp:TemplateField HeaderText="Role Name">
                                                <ItemTemplate>
                                                    <asp:Label ID="lblRole" runat="server" Text='<%#Container.DataItem %>' />
                                                </ItemTemplate>
                                            </asp:TemplateField>
                                        </Columns>
                                    </asp:GridView>
                                </td>
                            </tr>
                        </table>
                    </ContentTemplate>
                </asp:TabPanel>
                <asp:TabPanel ID="TabPanel2" runat="server">
                    <HeaderTemplate>Asign Role</HeaderTemplate>
                    <ContentTemplate>


                        <table align="center">
                            <tr>
                                <td><b>Select User:</b> </td>
                                <td>
                                    <asp:DropDownList ID="ddlUsers" runat="server" AutoPostBack="true" OnSelectedIndexChanged="ddlUsers_SelectedIndexChanged" /></td>
                            </tr>
                            <tr>
                                <td colspan="2">
                                    <asp:GridView ID="GridView1" runat="server" CssClass="Gridview" AutoGenerateColumns="false" Width="150">
                                        <HeaderStyle BackColor="#df5015" />
                                        <Columns>
                                            <asp:TemplateField>
                                                <ItemTemplate>
                                                    <asp:CheckBox ID="chkRole" runat="server" />
                                                </ItemTemplate>
                                            </asp:TemplateField>
                                            <asp:TemplateField HeaderText="Role Name">
                                                <ItemTemplate>
                                                    <asp:Label ID="lblRole" runat="server" Text="<%#Container.DataItem %>" />
                                                </ItemTemplate>
                                            </asp:TemplateField>
                                        </Columns>
                                    </asp:GridView>
                                </td>
                            </tr>
                            <tr>
                                <td colspan="2">
                                    <asp:Button ID="btnAssign" runat="server" Text="Assign or UnAssign" OnClick="btnAssign_Click" /></td>
                            </tr>
                        </table>
                        <div align="center">
                            <asp:Label ID="lblSuccess" runat="server" Font-Bold="true" />
                            <br />
                            <asp:Label ID="lblError" runat="server" Font-Bold="true" />
                        </div>


                    </ContentTemplate>
                </asp:TabPanel>
                <asp:TabPanel ID="TabPanel3" runat="server">
                    <HeaderTemplate>Change Password</HeaderTemplate>
                    <ContentTemplate>
                        <asp:ChangePassword ID="ChangePassword1" runat="server" Height="300px" CancelDestinationPageUrl="~/PageAdmin/Admin.aspx" ContinueDestinationPageUrl="~/PageAdmin/Admin.aspx"></asp:ChangePassword>
                    </ContentTemplate>
                </asp:TabPanel>
               

            </asp:TabContainer>
        </div>
    </div>
</asp:Content>

